### PR TITLE
kernel/sys: Move Multiboot2 to a separate file

### PR DESCRIPTION
**Pull request by lutherwenxu**
This makes space for future integration with other bootloader if required.
It also prevents Multiboot2-specific code from bloating up `boot_x64.v`.

### CODE REVIEW

**Comment by gabixdev** [comment]
resolve the conflicts, ensure it builds/boots and here we go

**Comment by donnisnoni95** [comment]
done

**Comment by medvednikov** [comment]
Please use squashing, not merging.

**Comment by atecce** [comment]
`rebase` ftw

**Pull request merged**
